CREATE USER demo WITH PASSWORD 'demo';
CREATE DATABASE accountdb OWNER demo;
CREATE DATABASE transferdb OWNER demo;
GRANT ALL PRIVILEGES ON DATABASE accountdb TO demo;
GRANT ALL PRIVILEGES ON DATABASE transferdb TO demo;
