spring:
  application:
    name: workflow
server:
  port: 8080
account:
  service:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:8081}
temporal:
  host: ${TEMPORAL_HOST:localhost}
logging:
  structured:
    format:
      console: ecs
